### ISSUE TITLE
Ponte Vioh

### ISSUE THREAD

**Issue by devswert** [eaperezej/xmage-decks#1]
Cuando vas a empezar a hacer algo de itsmybirthday o dinos? Oeee loco ya fuuuundete

**Comment by devswert** [comment]
https://github.com/eaperezej/itsmybirthday-today

**Comment by devswert** [comment]
Loco ya po fuuuuuuundete

**Comment by eaperezej** [comment]
say -v Jorge no

**Comment by devswert** [comment]
Me emperra

**Comment by cmoncadov** [comment]
say -v Jorge Hola amigos, soy el loyalink777, el mejor enviador de encuestas del universo, hoy les traigo mi top 10 de juegos de game boy, empecemos: 
10 -
![image](https://user-images.githubusercontent.com/35935770/40743960-0fa0e4d8-6421-11e8-8f1b-b29098ffa57b.png)
